version: '2.1'

services:
  tanu:
    image: tanuzou
    build: 
      context: .
      dockerfile: Dockerfile
    environment:
      - AWS_ACCESS_KEY_ID
      - AWS_SECRET_ACCESS_KEY
    ports:
      - "8000:8000"
    volumes:
      - ./base:/var/www/html
      - ./data:/data

