version: '2.1'

services:
  k8s-cli:
    image: k8s-cli
    build: 
      context: .
      dockerfile: Dockerfile
    environment:
      - AWS_ACCESS_KEY_ID
      - AWS_SECRET_ACCESS_KEY
    volumes:
      - ./data:/data